# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: 2
updates:
  # Dependencies for Maven
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "jakarta.platform:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.activation:jakarta.activation-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.annotation:jakarta.annotation-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.enterprise:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.servlet.*:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.ws.rs:jakarta.ws.rs-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.validation:jakarta.validation-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.glassfish.web:jakarta.servlet.jsp.jstl"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.omnifaces:omnifaces"
        update-types: [ "version-update:semver-major" ]

      - dependency-name: "org.springframework*:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "com.flowlogix:flowlogix-jee"
        update-types: [ "version-update:semver-major" ]

      - dependency-name: "org.eclipse.jetty:*"
        update-types: [ "version-update:semver-major" ]

  # Dependencies for Maven - on 1.12.x
  - package-ecosystem: 'maven'
    directory: '/'
    target-branch: '1.12.x'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "jakarta.servlet.*:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "javax.servlet:javax.servlet-api"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.glassfish.web:jakarta.servlet.jsp.jstl"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.glassfish.jersey.*:*"
        update-types: [ "version-update:semver-major" ]

      - dependency-name: "org.jasig.cas.client:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "org.slf4j:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.codehaus.groovy:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "ch.qos.logback:logback-classic"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "com.hazelcast:hazelcast"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.aspectj:*"
        update-types: [ "version-update:semver-patch" ]

      - dependency-name: "org.springframework*:*"
        update-types: [ "version-update:semver-major" ]

      - dependency-name: "org.eclipse.jetty:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "com.github.mjeanroy:junit-servers-jetty"
        update-types: [ "version-update:semver-minor" ]

  # Dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10

  # Dependencies for GitHub Actions - on 1.12.x
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: '1.12.x'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
